// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnkeqeikvtvpbdvbjxpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ua2VxZWlrdnR2cGJkdmJqeHBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDE5ODgsImV4cCI6MjA3MTk3Nzk4OH0.CGwn1PYad-QtUO3kqqGDgWyH95p1u9XetCELNWXdAqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});